info:
  version: '${project.version}'
  stage: dev

server:
  port: '${server.port}'

management:
  server:
    port: '${management.port}'
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: '${project.name}'
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  application:
    name: "${project.name}"
  output:
    ansi:
      enabled: always
  kafka:
    bootstrap-servers: localhost:9092
    topics:
      invoice: invoicing-events
    streams:
      application-id: kafka-exporter-business-metrics
      properties:
        auto.offset.reset: latest
        retries: 300
        retry.backoff.ms: 1000
        num.stream.threads: 7
        default.api.timeout.ms: 300000
        clean.timeout.sec: 20
        fixed.rate.timeout.ms: 60000

metrics:
  export-ms: 30000
  ttl:
    seconds: 3600
    min-lifetime-seconds: 120
    cleaner:
      enabled: false
      ms: 60000
